(() => {
  const $ = (s) => document.querySelector(s);
  const canvas = $('#game'), ctx = canvas.getContext('2d');
  const auth = $('#auth-screen'), screen = $('#game-screen'), form = $('#auth-form');
  const keys = new Set();
  const supabaseClient = window.GAME_SUPABASE && window.supabase ? window.supabase.createClient(window.GAME_SUPABASE.url, window.GAME_SUPABASE.publishableKey) : null;
  const chars = [
    { icon:'🐱', name:'Mèo ninja', color:'#a78bfa' }, { icon:'🐸', name:'Ếch phù thủy', color:'#76d99a' },
    { icon:'🤖', name:'Robot hộp', color:'#77ccec' }, { icon:'🦊', name:'Cáo lửa', color:'#ff9b64' },
    { icon:'🐼', name:'Gấu trúc', color:'#a0a9ba' }, { icon:'🦄', name:'Kỳ lân kẹo', color:'#ff87ba' }
  ];
  const botNames = ['BánhMìBay','BắpRang','MựcTím','CáMậpCon','GấuBông','ỚtHiểm','KemDâu','MèoÚ','CáoMơ','BắpCải'];
  const cosmetics = [
    {id:'cat',icon:'🐱',name:'Mèo ninja',color:'#a78bfa',price:0},
    {id:'fox',icon:'🦊',name:'Cáo neon',color:'#ff9b64',price:120},
    {id:'robot',icon:'🤖',name:'Robot kẹo',color:'#77ccec',price:180},
    {id:'unicorn',icon:'🦄',name:'Kỳ lân sao',color:'#ff87ba',price:250},
    {id:'panda',icon:'🐼',name:'Gấu trúc',color:'#a0a9ba',price:320},
    {id:'frog',icon:'🐸',name:'Ếch phù thủy',color:'#76d99a',price:400}
  ];
  const trails = [
    {id:'none',icon:'○',name:'Không dùng vệt',price:0,type:'none'},
    {id:'rainbow',icon:'🌈',name:'Vệt cầu vồng',price:120,type:'rainbow'},
    {id:'clover',icon:'☘️',name:'Cỏ may mắn',price:100,type:'clover'},
    {id:'chili',icon:'🌶️',name:'Vết tương ớt',price:100,type:'chili'},
    {id:'water',icon:'💧',name:'Vệt nước mát',price:90,type:'water'},
    {id:'stars',icon:'✨',name:'Sao lấp lánh',price:180,type:'stars'}
  ];
  const ROOM_TOPIC = 'game:street-lobby-1';
  const remotePlayers = new Map();
  let player, profile, currentUser = null, authMode = 'signup', bots = [], particles = [], trailParticles = [], holes = [], items = [], last = 0, gameTime = 0, itemTimer = 0, toastTimer, gameOn = false, roomChannel = null, lastBroadcastAt = 0, world = {w:2600,h:1800};
  const view = {x:0,y:0};
  function hash(s){ return [...s].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,7) >>> 0; }
  function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
  async function loadProfile(name){if(supabaseClient&&currentUser){const {data,error}=await supabaseClient.from('player_profiles').select('*').eq('id',currentUser.id).maybeSingle();if(!error&&data)return {name:data.display_name,coins:data.coins,owned:data.owned_skins||['cat'],ownedTrails:data.owned_trails||['none'],skin:data.skin||'cat',trail:data.trail||'none'};}try{const saved=JSON.parse(localStorage.getItem('qv-profile'));if(saved&&saved.name===name)return {...saved,owned:saved.owned||['cat'],ownedTrails:saved.ownedTrails||['none'],skin:saved.skin||'cat',trail:saved.trail||'none',coins:Number(saved.coins)||0};}catch{}return {name,coins:150,owned:['cat'],ownedTrails:['none'],skin:'cat',trail:'none'};}
  function saveProfile(){if(!profile)return;localStorage.setItem('qv-profile',JSON.stringify(profile));if(supabaseClient&&currentUser)supabaseClient.from('player_profiles').update({display_name:profile.name,skin:profile.skin,trail:profile.trail}).eq('id',currentUser.id);}
  function currentSkin(){return cosmetics.find(s=>s.id===profile?.skin)||cosmetics[0];}
  function currentTrail(){return trails.find(t=>t.id===profile?.trail)||trails[0];}
  function applySkin(entity){const skin=currentSkin();entity.icon=skin.icon;entity.color=skin.color;entity.skinName=skin.name;}
  function resize(){ canvas.width = innerWidth * devicePixelRatio; canvas.height = innerHeight * devicePixelRatio; ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); }
  addEventListener('resize',resize); resize();
  function createEntity(name, i, isBot=false){ const c=chars[i%chars.length]; return {name,icon:c.icon,color:c.color,x:180+Math.random()*(world.w-360),y:180+Math.random()*(world.h-360),r:isBot?22:25,hp:3,score:isBot?Math.floor(Math.random()*85)+10:0,dir:Math.random()*Math.PI*2,vx:0,vy:0,pushX:0,pushY:0,pushBoost:1,speedBoost:1,pushUntil:0,speedUntil:0,trailTimer:0,lastPusher:null,lastPushAt:0,hit:0,dead:false,isBot}; }
  async function start(name){profile=await loadProfile(name);const i=hash(profile.name)%chars.length;player=createEntity(profile.name,i);player.id=currentUser?.id||crypto.randomUUID();applySkin(player);remotePlayers.clear();bots=[];syncBots();particles=[];trailParticles=[];holes=[];items=[];gameTime=0;itemTimer=2;createRoomHoles();gameOn=true;auth.hidden=true;screen.hidden=false;$('.hint').classList.remove('hide');$('#player-name').textContent=profile.name;$('#avatar').textContent=player.icon;$('#character-name').textContent=player.skinName;setConnectionStatus('connecting');await joinRoom();toast('Đấu trường online: đẩy đối thủ vào hố đen!');setTimeout(()=>$('.hint').classList.add('hide'),6500);last=performance.now();requestAnimationFrame(loop);}
  function createRoomHoles(){const seed=hash(ROOM_TOPIC);const rand=n=>{const x=Math.sin(seed+n*999)*43758.5453;return x-Math.floor(x);};holes=Array.from({length:5},(_,i)=>({x:260+rand(i*2)*(world.w-520),y:220+rand(i*2+1)*(world.h-440),r:58+rand(i+30)*15,life:Infinity}));}
  function syncBots(){const wanted=Math.max(0,4-remotePlayers.size);while(bots.length>wanted)bots.pop();while(bots.length<wanted){const j=bots.length;bots.push(createEntity(botNames[j],(j+2)%chars.length,true));}}
  function setConnectionStatus(mode){const el=$('#connection-status');if(!el)return;el.className='connection-status '+mode;el.textContent=mode==='online'?`● ONLINE · ${remotePlayers.size+1} NGƯỜI`:mode==='connecting'?'● ĐANG KẾT NỐI':'● CHẾ ĐỘ BOT';}
  async function joinRoom(){if(!supabaseClient||!currentUser){setConnectionStatus('offline');return;}await leaveRoom();const channel=supabaseClient.channel(ROOM_TOPIC,{config:{private:true,presence:{key:currentUser.id},broadcast:{self:false,ack:false}}});roomChannel=channel;channel.on('broadcast',{event:'player-state'},({payload})=>receivePlayerState(payload)).on('broadcast',{event:'player-hit'},({payload})=>receivePlayerHit(payload)).on('broadcast',{event:'player-eliminated'},({payload})=>receiveElimination(payload)).on('presence',{event:'sync'},syncPresence).subscribe(async(status)=>{if(roomChannel!==channel)return;if(status==='SUBSCRIBED'){await channel.track({id:currentUser.id,name:profile.name,icon:player.icon,color:player.color,joinedAt:new Date().toISOString()});setConnectionStatus('online');broadcastState(true);}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){setConnectionStatus('offline');}});}
  async function leaveRoom(){if(!roomChannel)return;const oldChannel=roomChannel;roomChannel=null;try{await oldChannel.untrack();}catch{}await supabaseClient.removeChannel(oldChannel);remotePlayers.clear();}
  function syncPresence(){if(!roomChannel||!currentUser)return;const active=new Set();Object.values(roomChannel.presenceState()).flat().forEach(member=>{if(member.id&&member.id!==currentUser.id)active.add(member.id);});for(const id of remotePlayers.keys())if(!active.has(id))remotePlayers.delete(id);syncBots();setConnectionStatus('online');broadcastState(true);}
  function receivePlayerState(data){if(!data||data.id===currentUser?.id||typeof data.x!=='number'||typeof data.y!=='number')return;let remote=remotePlayers.get(data.id);if(!remote){remote=createEntity(String(data.name||'Người chơi').slice(0,16),hash(data.id)%chars.length);remote.id=data.id;remote.isRemote=true;remote.isBot=false;remote.x=data.x;remote.y=data.y;remote.targetX=data.x;remote.targetY=data.y;remotePlayers.set(data.id,remote);syncBots();setConnectionStatus('online');}remote.name=String(data.name||remote.name).slice(0,16);remote.icon=String(data.icon||remote.icon).slice(0,4);remote.color=/^#[0-9a-f]{6}$/i.test(data.color||'')?data.color:remote.color;remote.targetX=Math.max(remote.r,Math.min(world.w-remote.r,data.x));remote.targetY=Math.max(remote.r,Math.min(world.h-remote.r,data.y));remote.dir=Number(data.dir)||0;remote.score=Math.max(0,Number(data.score)||0);remote.dead=Boolean(data.dead);remote.lastSeen=performance.now();}
  function receivePlayerHit(data){if(!data||data.targetId!==currentUser?.id||!player||player.dead)return;const ix=Math.max(-420,Math.min(420,Number(data.impulseX)||0)),iy=Math.max(-420,Math.min(420,Number(data.impulseY)||0));player.pushX+=ix;player.pushY+=iy;player.lastPusher={id:data.fromId,name:String(data.fromName||'Đối thủ').slice(0,16),isRemote:true};player.lastPushAt=gameTime;}
  function receiveElimination(data){if(!data||data.killerId!==currentUser?.id||data.victimId===currentUser?.id)return;player.score+=15;toast(`Bạn đã hạ ${String(data.victimName||'đối thủ').slice(0,16)}! +15 điểm`);}
  function broadcastState(force=false){if(!roomChannel||!player||!currentUser)return;const now=performance.now();if(!force&&now-lastBroadcastAt<80)return;lastBroadcastAt=now;roomChannel.send({type:'broadcast',event:'player-state',payload:{id:currentUser.id,name:player.name,icon:player.icon,color:player.color,x:Math.round(player.x*10)/10,y:Math.round(player.y*10)/10,dir:Math.round(player.dir*100)/100,score:player.score,dead:player.dead}});}
  function setAuthMode(mode){authMode=mode;document.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('#name-field').hidden=mode==='signin';$('#name').required=mode==='signup';$('#password').autocomplete=mode==='signup'?'new-password':'current-password';$('#auth-submit').innerHTML=mode==='signup'?'TẠO TÀI KHOẢN <span>→</span>':'ĐĂNG NHẬP <span>→</span>';$('#auth-message').textContent=mode==='signup'?'Tài khoản lưu an toàn trên máy chủ.':'Đăng nhập để tiếp tục hồ sơ của bạn.';}
  async function submitAuth(e){e.preventDefault();if(!supabaseClient){$('#auth-message').textContent='Chưa kết nối được máy chủ. Vui lòng thử lại.';return;}const email=$('#email').value.trim(),password=$('#password').value,name=$('#name').value.trim(),button=$('#auth-submit');if(authMode==='signup'&&!name)return;button.disabled=true;button.textContent='ĐANG XỬ LÝ...';let result;if(authMode==='signup')result=await supabaseClient.auth.signUp({email,password,options:{data:{display_name:name}}});else result=await supabaseClient.auth.signInWithPassword({email,password});button.disabled=false;if(result.error){$('#auth-message').textContent=result.error.message;setAuthMode(authMode);return;}if(!result.data.session){$('#auth-message').textContent='Hãy mở email để xác nhận tài khoản, sau đó quay lại đăng nhập.';setAuthMode('signin');return;}currentUser=result.data.user;localStorage.setItem('qv-name',authMode==='signup'?name:currentUser.user_metadata?.display_name||email.split('@')[0]);await start(authMode==='signup'?name:currentUser.user_metadata?.display_name||email.split('@')[0]);}
  form.addEventListener('submit',submitAuth);
  document.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
  $('#leave-btn').onclick=async()=>{saveProfile();gameOn=false;await leaveRoom();if(supabaseClient)await supabaseClient.auth.signOut();currentUser=null;screen.hidden=true;auth.hidden=false;setAuthMode('signin');};
  addEventListener('beforeunload',()=>{if(roomChannel)roomChannel.untrack();});
  const old=localStorage.getItem('qv-name'); if(old) $('#name').value=old;
  if(supabaseClient)supabaseClient.auth.getSession().then(async({data})=>{if(!data.session)return;currentUser=data.session.user;await start(currentUser.user_metadata?.display_name||currentUser.email?.split('@')[0]||'Nguoi choi');});
  $('#shop-btn').onclick=()=>{renderShop();$('#shop-modal').hidden=false;};
  $('#ad-btn').onclick=()=>$('#ad-modal').hidden=false;
  document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).hidden=true);
  $('#watch-ad-btn').onclick=watchRewardAd;
  addEventListener('keydown',e=>{ if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);}); addEventListener('keyup',e=>keys.delete(e.code)); addEventListener('blur',()=>keys.clear());
  function shopCard(item,kind){const isTrail=kind==='trail',owned=(isTrail?profile.ownedTrails:profile.owned).includes(item.id),active=isTrail?profile.trail===item.id:profile.skin===item.id,background=isTrail?'#fff0d8':`${item.color}33`;return `<article class="skin-card ${active?'active':''}"><div class="skin-icon" style="background:${background}">${item.icon}</div><div><b>${item.name}</b><small>${item.price?`🪙 ${item.price}`:'Miễn phí'}</small></div><button data-kind="${kind}" data-item="${item.id}" ${active?'disabled':''}>${active?'ĐANG DÙNG':owned?'TRANG BỊ':`MUA ${item.price} XU`}</button></article>`;}
  function renderShop(){const grid=$('#shop-grid');grid.innerHTML=`<h3 class="shop-heading">NHÂN VẬT</h3>${cosmetics.map(s=>shopCard(s,'skin')).join('')}<h3 class="shop-heading">VỆT DI CHUYỂN</h3>${trails.map(t=>shopCard(t,'trail')).join('')}`;grid.querySelectorAll('[data-item]').forEach(button=>button.onclick=()=>buyOrEquip(button.dataset.item,button.dataset.kind));}
  function buyOrEquip(id,kind='skin'){const isTrail=kind==='trail',item=(isTrail?trails:cosmetics).find(s=>s.id===id);if(!item)return;const ownedKey=isTrail?'ownedTrails':'owned',activeKey=isTrail?'trail':'skin';if(!profile[ownedKey].includes(id)){if(currentUser){toast('Shop thật sẽ mở sau khi máy chủ trận đấu hoàn tất.');return;}if(profile.coins<item.price){toast('Bạn chưa đủ xu để mua vật phẩm này.');return;}profile.coins-=item.price;profile[ownedKey].push(id);toast('Đã mở khóa '+item.name+'!');}profile[activeKey]=id;if(!isTrail){applySkin(player);$('#avatar').textContent=player.icon;$('#character-name').textContent=player.skinName;}saveProfile();renderShop();updateUI();}
  function watchRewardAd(){if(currentUser){$('#ad-modal').hidden=true;toast('Quảng cáo có thưởng sẽ mở cùng máy chủ trận đấu.');return;}const button=$('#watch-ad-btn');if(button.disabled)return;button.disabled=true;let seconds=3;button.textContent=`ĐANG XEM... ${seconds}s`;const timer=setInterval(()=>{seconds--;button.textContent=seconds?`ĐANG XEM... ${seconds}s`:'ĐANG NHẬN THƯỞNG';if(seconds>0)return;clearInterval(timer);button.disabled=false;button.textContent='XEM & NHẬN XU';profile.coins+=20;saveProfile();$('#ad-modal').hidden=true;updateUI();toast('Bạn nhận được 20 xu!');},1000);}
  function eliminate(who, from){ if(who.dead)return;who.dead=true;who.score=Math.max(0,who.score-8);burst(who.x,who.y,'#2b1a55',22);if(from&&from!==who){if(from.isRemote&&who===player){toast(from.name+' đã đẩy bạn vào hố đen!');roomChannel?.send({type:'broadcast',event:'player-eliminated',payload:{victimId:currentUser.id,victimName:player.name,killerId:from.id}});}else{from.score+=15;if(from===player){if(!currentUser){profile.coins+=10;saveProfile();toast('Bạn đã đẩy '+who.name+' vào hố đen! +10 xu');}else toast('Bạn đã đẩy '+who.name+' vào hố đen!');}else toast(who.name+' đã đẩy bạn vào hố đen!');}}else if(who===player)toast('Bạn đã rơi vào hố đen!');broadcastState(true);if(who===player)respawnPlayer();else setTimeout(()=>respawnBot(who),2200);}
  function holeTarget(){return holes.length||5;}
  function spawnHole(){let x,y,tries=0;do{x=150+Math.random()*(world.w-300);y=150+Math.random()*(world.h-300);tries++;}while(player&&Math.hypot(x-player.x,y-player.y)<300&&tries<20);holes.push({x,y,r:54+Math.random()*20,life:14+Math.random()*7});}
  function spawnItem(){let x,y,tries=0;do{x=80+Math.random()*(world.w-160);y=80+Math.random()*(world.h-160);tries++;}while(holes.some(h=>Math.hypot(x-h.x,y-h.y)<h.r*3)&&tries<25);items.push({x,y,r:15,type:Math.random()<.5?'push':'speed',life:16});}
  function safeRespawn(e){let x,y,tries=0;do{x=120+Math.random()*(world.w-240);y=120+Math.random()*(world.h-240);tries++;}while(holes.some(h=>Math.hypot(x-h.x,y-h.y)<h.r*3)&&tries<30);e.x=x;e.y=y;e.vx=e.vy=e.pushX=e.pushY=0;e.lastPusher=null;}
  function respawnPlayer(){ $('#respawn').hidden=false;let n=3;$('#respawn-count').textContent=n;const t=setInterval(()=>{$('#respawn-count').textContent=--n;if(n<=0){clearInterval(t);player.hp=3;player.dead=false;safeRespawn(player);$('#respawn').hidden=true;broadcastState(true);toast('Bạn đã hồi sinh!');}},1000); }
  function respawnBot(b){b.hp=3;b.dead=false;safeRespawn(b);}
  function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,t:.4+Math.random()*.25,c});}
  function update(dt){if(!player)return;gameTime+=dt;[player,...bots].forEach(e=>{if(!e)return;if(e.pushUntil&&gameTime>=e.pushUntil){e.pushBoost=1;e.pushUntil=0;}if(e.speedUntil&&gameTime>=e.speedUntil){e.speedBoost=1;e.speedUntil=0;}});itemTimer-=dt;if(itemTimer<=0){if(items.length<5)spawnItem();itemTimer=2.5+Math.random()*3;}items=items.filter(item=>(item.life-=dt)>0);
    let dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(dx||dy){let l=Math.hypot(dx,dy);player.vx=dx/l*230*player.speedBoost;player.vy=dy/l*230*player.speedBoost;player.dir=Math.atan2(dy,dx)}else{player.vx*=.72;player.vy*=.72}move(player,dt);
    bots.forEach(b=>{if(b.dead)return;let d=Math.hypot(player.x-b.x,player.y-b.y),a;if(d<360)a=Math.atan2(player.y-b.y,player.x-b.x);else if(Math.random()<.012)a=Math.random()*6.28;else a=b.dir+(Math.random()-.5)*.06;b.dir=a??b.dir;b.vx=Math.cos(b.dir)*(d<360?138:76)*b.speedBoost;b.vy=Math.sin(b.dir)*(d<360?138:76)*b.speedBoost;move(b,dt);if(Math.random()<.002)b.score+=1;});
    for(const remote of remotePlayers.values()){remote.x+=(remote.targetX-remote.x)*Math.min(1,dt*12);remote.y+=(remote.targetY-remote.y)*Math.min(1,dt*12);}resolvePushes();resolveRemotePushes();applyHoleGravity(dt);checkHoles();collectItems();updateTrail(dt);trailParticles=trailParticles.filter(p=>(p.t-=dt)>0);particles=particles.filter(p=>(p.t-=dt)>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=60*dt});view.x+=(player.x-innerWidth/2-view.x)*Math.min(1,dt*5);view.y+=(player.y-innerHeight/2-view.y)*Math.min(1,dt*5);broadcastState();updateUI();}
  function move(e,dt){if(e.dead)return;e.x=Math.max(e.r,Math.min(world.w-e.r,e.x+(e.vx+e.pushX)*dt));e.y=Math.max(e.r,Math.min(world.h-e.r,e.y+(e.vy+e.pushY)*dt));e.pushX*=Math.pow(.002,dt);e.pushY*=Math.pow(.002,dt);}
  function resolvePushes(){const fighters=[player,...bots].filter(e=>e&&!e.dead);for(let i=0;i<fighters.length;i++)for(let j=i+1;j<fighters.length;j++){const a=fighters[i],b=fighters[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(d>=min)continue;const nx=dx/d,ny=dy/d,overlap=min-d;a.x-=nx*overlap*.48;a.y-=ny*overlap*.48;b.x+=nx*overlap*.52;b.y+=ny*overlap*.52;const speedA=Math.hypot(a.vx+a.pushX,a.vy+a.pushY),speedB=Math.hypot(b.vx+b.pushX,b.vy+b.pushY),pusher=speedA>=speedB?a:b,pushed=pusher===a?b:a,force=(105+Math.abs(speedA-speedB)*.32)*pusher.pushBoost;a.pushX-=nx*force*.3;a.pushY-=ny*force*.3;b.pushX+=nx*force*.7;b.pushY+=ny*force*.7;pushed.lastPusher=pusher;pushed.lastPushAt=gameTime;}}
  function resolveRemotePushes(){if(!roomChannel||player.dead)return;for(const remote of remotePlayers.values()){if(remote.dead)continue;const dx=remote.x-player.x,dy=remote.y-player.y,d=Math.hypot(dx,dy)||.01,min=player.r+remote.r;if(d>=min)continue;const nx=dx/d,ny=dy/d,overlap=min-d;player.x-=nx*overlap*.55;player.y-=ny*overlap*.55;const localSpeed=Math.hypot(player.vx+player.pushX,player.vy+player.pushY),remoteSpeed=Math.hypot((remote.targetX-remote.x)*12,(remote.targetY-remote.y)*12),force=115+Math.abs(localSpeed-remoteSpeed)*.28,now=performance.now();if(localSpeed>=remoteSpeed){if(!remote.lastHitSent||now-remote.lastHitSent>160){remote.lastHitSent=now;roomChannel.send({type:'broadcast',event:'player-hit',payload:{targetId:remote.id,fromId:currentUser.id,fromName:player.name,impulseX:nx*force*.75,impulseY:ny*force*.75}});}}else{player.pushX-=nx*force*.7;player.pushY-=ny*force*.7;player.lastPusher=remote;player.lastPushAt=gameTime;}}}
  function applyHoleGravity(dt){for(const e of [player,...bots]){if(!e||e.dead)continue;for(const h of holes){const dx=h.x-e.x,dy=h.y-e.y,d=Math.hypot(dx,dy)||.01,reach=h.r*3;if(d>=reach)continue;const pull=Math.pow(1-d/reach,2)*1050;e.pushX+=dx/d*pull*dt;e.pushY+=dy/d*pull*dt;}}}
  function collectItems(){for(const e of [player,...bots]){if(!e||e.dead)continue;for(let i=items.length-1;i>=0;i--){const item=items[i];if(Math.hypot(e.x-item.x,e.y-item.y)>e.r+item.r)continue;items.splice(i,1);if(item.type==='push'){e.pushBoost=1.05;e.pushUntil=gameTime+60;}else{e.speedBoost=1.05;e.speedUntil=gameTime+60;}burst(e.x,e.y,item.type==='push'?'#ff7aa2':'#ffe263',14);if(e===player)toast(item.type==='push'?'Lực đẩy +5% trong 60 giây!':'Tốc độ +5% trong 60 giây!');}}}
  function updateTrail(dt){if(!player||player.dead)return;const trail=currentTrail(),speed=Math.hypot(player.vx+player.pushX,player.vy+player.pushY);if(trail.type==='none'||speed<28)return;player.trailTimer-=dt;if(player.trailTimer>0)return;player.trailTimer=.065;const behind=player.r*.75;trailParticles.push({type:trail.type,x:player.x-Math.cos(player.dir)*behind+(Math.random()-.5)*7,y:player.y-Math.sin(player.dir)*behind+(Math.random()-.5)*7,t:1,max:1,hue:(gameTime*150)%360,spin:Math.random()*6.28});if(trailParticles.length>110)trailParticles.shift();}
  function checkHoles(){for(const e of [player,...bots]){if(!e||e.dead)continue;for(const h of holes)if(Math.hypot(e.x-h.x,e.y-h.y)<h.r){const pusher=gameTime-e.lastPushAt<1.35?e.lastPusher:null;eliminate(e,pusher);break;}}}
  function updateUI(){const list=[player,...remotePlayers.values(),...bots].sort((a,b)=>b.score-a.score);$('#leader-name').textContent=list[0].name;$('#ranking').innerHTML=list.slice(0,5).map(p=>`<li class="${p===player?'me':''}"><span>${escapeHtml(p.icon)} ${escapeHtml(p.name)}</span><b>${Math.max(0,Number(p.score)||0)}</b></li>`).join('');const pushLeft=Math.max(0,Math.ceil(player.pushUntil-gameTime)),speedLeft=Math.max(0,Math.ceil(player.speedUntil-gameTime));$('#boosts').textContent=pushLeft||speedLeft?`💥 ${pushLeft?`+5% ${pushLeft}s`:'ĐẨY 100%'} · ⚡ ${speedLeft?`+5% ${speedLeft}s`:'TỐC 100%'}`:'💥 ĐẨY 100% · ⚡ TỐC 100%';$('#coin-count').textContent=profile?.coins||0;}
  function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(-view.x,-view.y);drawGround();holes.forEach(drawHole);items.forEach(drawItem);trailParticles.forEach(drawTrail);[...bots,...remotePlayers.values(),player].filter(Boolean).forEach(drawEntity);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.t*2);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill();});ctx.globalAlpha=1;ctx.restore();}
  function drawGround(){ctx.fillStyle='#98dfef';ctx.fillRect(view.x,view.y,innerWidth,innerHeight);ctx.fillStyle='#8acfdc';for(let x=Math.floor(view.x/120)*120;x<view.x+innerWidth+120;x+=120)for(let y=Math.floor(view.y/120)*120;y<view.y+innerHeight+120;y+=120){ctx.beginPath();ctx.arc(x+30+(Math.sin(y)*15),y+45,2,0,7);ctx.fill();}ctx.strokeStyle='#78bfcb';ctx.lineWidth=10;ctx.strokeRect(18,18,world.w-36,world.h-36);}
  function drawHole(h){ctx.save();ctx.translate(h.x,h.y);ctx.fillStyle='#45236e66';ctx.beginPath();ctx.arc(0,4,h.r+8,0,7);ctx.fill();ctx.fillStyle='#1b1234';ctx.beginPath();ctx.arc(0,0,h.r,0,7);ctx.fill();ctx.strokeStyle='#8c53d5';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,h.r-4,0,7);ctx.stroke();ctx.strokeStyle='#c991ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,h.r-10,0,7);ctx.stroke();ctx.restore();}
  function drawItem(item){ctx.save();ctx.translate(item.x,item.y);ctx.fillStyle=item.type==='push'?'#ff6d98':'#ffca4a';ctx.beginPath();ctx.moveTo(0,-item.r);ctx.lineTo(item.r,0);ctx.lineTo(0,item.r);ctx.lineTo(-item.r,0);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.font='17px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(item.type==='push'?'💥':'⚡',0,1);ctx.restore();}
  function drawTrail(p){const alpha=Math.max(0,p.t/p.max);ctx.save();ctx.globalAlpha=alpha*.82;ctx.translate(p.x,p.y);if(p.type==='rainbow'){ctx.fillStyle=`hsl(${p.hue},88%,62%)`;ctx.beginPath();ctx.arc(0,0,8*alpha+2,0,7);ctx.fill();}else if(p.type==='clover'){ctx.font=`${18*alpha+5}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('☘',0,1);}else if(p.type==='chili'){ctx.fillStyle='#e44445';ctx.beginPath();ctx.arc(0,0,8*alpha+2,0,7);ctx.fill();ctx.fillStyle='#ff9e99';ctx.beginPath();ctx.arc(-2,-2,2,0,7);ctx.fill();}else if(p.type==='water'){ctx.strokeStyle='#55c9ed';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,10*alpha+2,5*alpha+1,0,0,7);ctx.stroke();}else if(p.type==='stars'){ctx.rotate(p.spin);ctx.fillStyle='#fff6a1';ctx.font=`${17*alpha+6}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('✦',0,0);}ctx.restore();}
  function drawEntity(e){if(e.dead)return;ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle='#39587a44';ctx.beginPath();ctx.ellipse(3,20,e.r,8,0,0,7);ctx.fill();ctx.rotate(e.dir);ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(0,0,e.r,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#ffffffa8';ctx.beginPath();ctx.arc(e.r-5,0,4,0,7);ctx.fill();ctx.rotate(-e.dir);ctx.font=`${e.isBot?29:34}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(e.icon,0,1);ctx.restore();ctx.font='800 13px Nunito';ctx.textAlign='center';ctx.fillStyle='#263b58';ctx.fillText(e.name,e.x,e.y-e.r-15);}
  function loop(ts){if(!gameOn)return;let dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop);}
  function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200);}
})();
